name: Build Mongo Plugin

on:
  workflow_dispatch:
  push:
    paths:
      - "plugins/main.go"
      - "plugins/go.mod"
      - "plugins/go.sum"
      - ".github/workflows/build-mongo.yml"

jobs:
  build-macos-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "v1.26.2"

      - run: go mod tidy

      - name: Build macOS arm64 .dylib
        run: |
          CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 \
          go build -buildmode=c-shared -ldflags="-s -w" -o tiny_mongo_arm64.dylib mongodb.go

      - uses: actions/upload-artifact@v4
        with:
          name: tiny_mongo_macos_arm64
          path: tiny_mongo_arm64.dylib